mkdir models 
cd models
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/4x_fatal_Anime_500000_G.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_pro-conservative-up2x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_pro-conservative-up3x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_pro-denoise3x-up2x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_pro-denoise3x-up3x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_pro-no-denoise3x-up2x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_pro-no-denoise3x-up3x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up2x-latest-conservative.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up2x-latest-denoise1x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up2x-latest-denoise2x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up2x-latest-denoise3x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up2x-latest-no-denoise.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up3x-latest-conservative.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up3x-latest-denoise3x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up3x-latest-no-denoise.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up4x-latest-conservative.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up4x-latest-denoise3x.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/cugan_up4x-latest-no-denoise.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/dpir_drunet_color.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/dpir_drunet_deblocking_color.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/dpir_drunet_deblocking_grayscale.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/dpir_drunet_gray.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/realesr-animevideov3.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/RealESRGANv2-animevideo-xsx2_opset13.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/RealESRGANv2-animevideo-xsx2_opset15.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/RealESRGANv2-animevideo-xsx4.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/RealESRGAN_x4plus_anime_6B.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/sudo_UltraCompact_2x_1.121.175_G_opset13.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/sudo_UltraCompact_2x_1.121.175_G_opset14.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/sudo_UltraCompact_2x_1.121.175_G_opset15.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_anime_style_art_noise1_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_anime_style_art_noise2_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_anime_style_art_rgb_noise0_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_anime_style_art_rgb_noise1_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_anime_style_art_rgb_noise2_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_anime_style_art_rgb_noise3_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_anime_style_art_rgb_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_anime_style_art_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise0_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise0_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise1_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise1_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise1_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise2_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise2_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise3_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_noise3_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_cunet_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_photo_noise0_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_photo_noise0_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_photo_noise1_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_photo_noise2_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_photo_noise3_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_photo_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_ukbench_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_anime_style_art_rgb_noise0_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_anime_style_art_rgb_noise1_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_anime_style_art_rgb_noise2_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_anime_style_art_rgb_noise3_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_anime_style_art_rgb_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_photo_noise0_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_photo_noise1_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_photo_noise2_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_photo_noise3_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upconv_7_photo_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upresnet10_noise0_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upresnet10_noise1_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upresnet10_noise2_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upresnet10_noise3_scale2.0x_model.onnx
wget https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/waifu2x_upresnet10_scale2.0x_model.onnx
